"""empty message

Revision ID: 26cd7f2040cd
Revises: 7a29a1add10b
Create Date: 2020-08-09 23:23:35.458458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26cd7f2040cd'
down_revision = '7a29a1add10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('enrollment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instructor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='enrollment_course_id_fkey'),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructor.id'], name='enrollment_instructor_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='enrollment_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='enrollment_pkey')
    )
    op.drop_table('Enrollment')
    # ### end Alembic commands ###
