"""empty message

Revision ID: 7a29a1add10b
Revises: 636c86468ced
Create Date: 2020-08-09 23:20:57.630046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a29a1add10b'
down_revision = '636c86468ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollment', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('enrollment', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('enrollment', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollment', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('enrollment', 'instructor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('enrollment', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
