"""empty message

Revision ID: fc421d5a5590
Revises: 212ab76acaf3
Create Date: 2020-08-23 10:19:06.514577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc421d5a5590'
down_revision = '212ab76acaf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructor', sa.Column('qualification', sa.String(), nullable=True))
    op.drop_column('instructor', 'qualifiaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructor', sa.Column('qualifiaction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('instructor', 'qualification')
    # ### end Alembic commands ###
